### PR TITLE
Us 203

### PR DESCRIPTION
**Pull request by ccqian-asu**
## Objective
Added the frontend of the login. 

## Detailed Description
This is the most recent version of the login page that is correctly centered. It does not include the backend postgres login. Currently it will flip the isAuthenticated variable but the routes are not re-rendered so the navbar will not change but if you attempt to access the login page again it will show you as already being logged in.

## Screenshot (if applicable)
image

## How to Test (if applicable)

1. Click on "Sign-in" on top right.
2. Login with any fake credentials that comply with minimum password requirements
3. You will be informed via alertbox that you are logged in (Placeholder)
4. Click "Sign-in" again to receive a notice that you are already logged in

## Tests (if added)
NA

## Requirements
[Taiga User Story](https://tree.taiga.io/project/cbrobsto-iron-db/us/174)
[Taiga Task](https://tree.taiga.io/project/cbrobsto-iron-db/task/203)

### CODE REVIEW

**Review by mjidris — COMMENTED** [review]
The login functionality works as expected. I see the alert as described. When I click the sign in button again, I do see the `h1` element telling me I'm already signed in. 

A couple thoughts:
- The top of the `h1` element is partially behind the navbar. I ran into the same issue with the error message. It is true that the max top margin for a bootstrap class (`mt-5` I believe) is about `3rem`. For the error page, I worked around this by giving my error message a custom class and adding giving it a top margin of `6rem` I believe in `styles/App.css`.
- There's nearly 2 million lines being checked in here. All the `.vscode/`, `coverage/`, `.DS_Store`, and `node_modules/` files don't need to be here. #22 has a top-level `.gitignore` file to ignore all these except for the `coverage/` files so you can consider adding that here.

**Comment by StellaJaneRasmussen** [comment]
I'll just echo what Mohamed put. Overall, it looks good, but we definitely need to update the `.gitignore` file so we're not checking in all of this other stuff, especially `node_modules/`.

**Comment by ccqian-asu** [comment]
Added project level .gitignore and fixed styling issue by conforming my spacing from the login form to the logged in message.

**Review by StellaJaneRasmussen — APPROVED** [review]
Alright, I think we're good now. I'm *much* less concerned about 15,000 LOC than 1.7 million.

**Review by mjidris — APPROVED** [review]
👍

**Pull request merged**
