### PR TITLE
Us 231

### PR DESCRIPTION
**Pull request by StellaJaneRasmussen**
## Objective
Get React-to-Express requesting proxy working properly within Docker network.

## Detailed Description
In order to get proxying working for easier API calls in React, I had to set up the proxy to point to the API container on the internal Docker network. To see the primary code involved in this change, take a look at `client/package.json`. Towards the bottom, you'll see `http://api:3000`.

## Screenshot (if applicable)
N/A

## How to Test (if applicable)
After rebuilding the project, you'll be able to trace the network requests in the Chrome dev tools and see that the login request is being passed to `localhost:8001/login`, which is then proxied into the API. 

## Tests (if added)
N/A

## Requirements
[US-231](https://tree.taiga.io/project/cbrobsto-iron-db/us/231)
[T-252](https://tree.taiga.io/project/cbrobsto-iron-db/task/252)

### CODE REVIEW

**Review by mjidris — COMMENTED** [review]
I tried testing this out but I got this proxy error:
```
Proxy error: Could not proxy request /login from localhost:8000 to http://api:3000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
```

I did run a clean install, but I wonder if I may need to try that again or something is botching this in security settings or something.

**Comment by StellaJaneRasmussen** [comment]
Good catch, Mohamed. I know what needs fixed. I just have the wrong endpoint being called, and forgot to commit the right one. I'll push that change up now.

**Comment by StellaJaneRasmussen** [comment]
Alright @mjidris, I just tried rebuilding it after merging the `react-migration` branch into this one, and it seemed to work for me.

**Comment by mjidris** [comment]
Perfect! Let me re-test.

**Review by ccqian-asu — APPROVED** [review]

**Review by CBrobsto — APPROVED** [review]
image
Successfully shows localhost:8001/login in the request header. 
Steps for testing: 
Test on react-migration branch > delete node modules > checkout US-231> fresh install 
./iron.sh -l > go to localhost:8001 in chrome (do not use npm start or install)

**Pull request merged**
