### PR TITLE
Us 116

### PR DESCRIPTION
**Pull request by StellaJaneRasmussen**
## Objective
Set up the project install to build the React environment simultaneously with the API and Postgres.

## Detailed Description
Move the `docker-compose.yml` file and `iron.sh` file to root and configure to also build React.

## How to Test (if applicable)
1. Run `iron.sh -i` in the root of the project.
2. Check `localhost:8001` to verify that React has built properly.
3. Check `localhost:3001` to verify that the previous web application has built properly (excluding gulp). 
## Requirements
[Taiga User Story](https://tree.taiga.io/project/cbrobsto-iron-db/us/116)
[Taiga Task](https://tree.taiga.io/project/cbrobsto-iron-db/task/129)
[Taiga Task](https://tree.taiga.io/project/cbrobsto-iron-db/task/130)
[Taiga Task](https://tree.taiga.io/project/cbrobsto-iron-db/task/131)
[Taiga Task](https://tree.taiga.io/project/cbrobsto-iron-db/task/132)
[Taiga Task](https://tree.taiga.io/project/cbrobsto-iron-db/task/133)

### CODE REVIEW

**Comment by mjidris** [comment]
Was taking a look at this PR. The react app loads just fine, but I was having issues with the main website. This was after doing a full `docker system prune -a` and a reinstall via the `iron.sh` script. The main site is getting a 500 response from the server suggesting there may have been an error on my side when reinstalling or rebuilding the docker images.

I'll take a closer look tomorrow to see if I can figure out the root cause since I'm going to strongly assume that you're not getting that error.

**Comment by StellaJaneRasmussen** [comment]
@mjidris If you run `docker logs postgres`, what output do you get? You might actually be running into the same Postgres issue I am. If that's the case, it might not just be my machine.

**Comment by mjidris** [comment]
For `docker logs postgres` I get:
```
2019-11-17 04:21:06.961 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-11-17 04:21:06.961 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2019-11-17 04:21:06.964 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-11-17 04:21:07.068 UTC [18] LOG:  database system was shut down at 2019-11-17 04:20:58 UTC
2019-11-17 04:21:07.100 UTC [1] LOG:  database system is ready to accept connections
2019-11-17 04:21:07.158 UTC [25] LOG:  incomplete startup packet
2019-11-17 04:21:11.362 UTC [32] FATAL:  role "user" does not exist
2019-11-17 04:21:21.524 UTC [38] FATAL:  role "user" does not exist
2019-11-17 04:21:31.692 UTC [44] FATAL:  role "user" does not exist
2019-11-17 04:21:37.220 UTC [45] FATAL:  password authentication failed for user "user"
2019-11-17 04:21:37.220 UTC [45] DETAIL:  Role "user" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
2019-11-17 04:21:37.859 UTC [46] FATAL:  password authentication failed for user "user"
2019-11-17 04:21:37.859 UTC [46] DETAIL:  Role "user" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
2019-11-17 04:21:38.080 UTC [47] FATAL:  password authentication failed for user "user"
2019-11-17 04:21:38.080 UTC [47] DETAIL:  Role "user" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
2019-11-17 04:21:38.292 UTC [48] FATAL:  password authentication failed for user "user"
2019-11-17 04:21:38.292 UTC [48] DETAIL:  Role "user" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
2019-11-17 04:21:38.522 UTC [49] FATAL:  password authentication failed for user "user"
2019-11-17 04:21:38.522 UTC [49] DETAIL:  Role "user" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
2019-11-17 04:21:38.703 UTC [50] FATAL:  password authentication failed for user "user"
2019-11-17 04:21:38.703 UTC [50] DETAIL:  Role "user" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
2019-11-17 04:21:38.875 UTC [51] FATAL:  password authentication failed for user "user"
2019-11-17 04:21:38.875 UTC [51] DETAIL:  Role "user" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
2019-11-17 04:21:39.072 UTC [52] FATAL:  password authentication failed for user "user"
2019-11-17 04:21:39.072 UTC [52] DETAIL:  Role "user" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
2019-11-17 04:21:39.253 UTC [53] FATAL:  password authentication failed for user "user"
2019-11-17 04:21:39.253 UTC [53] DETAIL:  Role "user" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
2019-11-17 04:21:41.609 UTC [54] FATAL:  password authentication failed for user "user"
2019-11-17 04:21:41.609 UTC [54] DETAIL:  Role "user" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
2019-11-17 04:21:41.612 UTC [55] FATAL:  password authentication failed for user "user"
2019-11-17 04:21:41.612 UTC [55] DETAIL:  Role "user" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
2019-11-17 04:21:41.613 UTC [56] FATAL:  password authentication failed for user "user"
2019-11-17 04:21:41.613 UTC [56] DETAIL:  Role "user" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
2019-11-17 04:21:41.875 UTC [62] FATAL:  role "user" does not exist
2019-11-17 04:21:44.419 UTC [63] FATAL:  password authentication failed for user "user"
2019-11-17 04:21:44.419 UTC [63] DETAIL:  Role "user" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
2019-11-17 04:21:52.021 UTC [70] FATAL:  role "user" does not exist
2019-11-17 04:22:02.177 UTC [77] FATAL:  role "user" does not exist
2019-11-17 04:22:12.327 UTC [83] FATAL:  role "user" does not exist
2019-11-17 04:22:22.448 UTC [89] FATAL:  role "user" does not exist
2019-11-17 04:22:32.586 UTC [96] FATAL:  role "user" does not exist
2019-11-17 04:22:42.748 UTC [103] FATAL:  role "user" does not exist
2019-11-17 04:22:52.886 UTC [109] FATAL:  role "user" does not exist
2019-11-17 04:23:03.018 UTC [116] FATAL:  role "user" does not exist
2019-11-17 04:23:11.913 UTC [117] FATAL:  password authentication failed for user "user"
2019-11-17 04:23:11.913 UTC [117] DETAIL:  Role "user" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
2019-11-17 04:23:12.163 UTC [118] FATAL:  password authentication failed for user "user"
2019-11-17 04:23:12.163 UTC [118] DETAIL:  Role "user" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
2019-11-17 04:23:12.389 UTC [119] FATAL:  password authentication failed for user "user"
2019-11-17 04:23:12.389 UTC [119] DETAIL:  Role "user" does not exist.
        Connection matched pg_hba.conf line 95: "host all all all md5"
2019-11-17 04:23:13.134 UTC [125] FATAL:  role "user" does not exist
2019-11-17 04:23:23.304 UTC [131] FATAL:  role "user" does not exist
2019-11-17 04:23:33.438 UTC [138] FATAL:  role "user" does not exist
2019-11-17 04:23:43.586 UTC [146] FATAL:  role "user" does not exist
2019-11-17 04:23:53.739 UTC [153] FATAL:  role "user" does not exist
2019-11-17 04:24:03.879 UTC [160] FATAL:  role "user" does not exist
2019-11-17 04:24:14.018 UTC [167] FATAL:  role "user" does not exist
2019-11-17 04:24:24.180 UTC [174] FATAL:  role "user" does not exist
2019-11-17 04:24:34.331 UTC [181] FATAL:  role "user" does not exist
2019-11-17 04:24:44.472 UTC [188] FATAL:  role "user" does not exist
2019-11-17 04:24:54.624 UTC [194] FATAL:  role "user" does not exist
2019-11-17 04:25:04.761 UTC [201] FATAL:  role "user" does not exist
2019-11-17 04:25:14.902 UTC [207] FATAL:  role "user" does not exist
2019-11-17 04:25:25.049 UTC [213] FATAL:  role "user" does not exist
2019-11-17 04:25:35.231 UTC [219] FATAL:  role "user" does not exist
2019-11-17 04:25:45.367 UTC [226] FATAL:  role "user" does not exist
2019-11-17 04:25:55.511 UTC [233] FATAL:  role "user" does not exist
```

On `docker ps` I get:
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                    PORTS                      NAMES
40b1a67f0cc1        irondb_client       "docker-entrypoint.s…"   27 seconds ago      Up 26 seconds             127.0.0.1:8001->8000/tcp   irondb_client_1
39ccd7242f90        irondb_api          "./docker/wait-for-i…"   28 seconds ago      Up 27 seconds             127.0.0.1:3001->3000/tcp   irondb_web
c437574d00eb        irondb_pgdb         "docker-entrypoint.s…"   30 seconds ago      Up 28 seconds (healthy)   127.0.0.1:5433->5432/tcp   postgres
```

The issue seems to be persistent.

**Comment by mjidris** [comment]
In just reading this, it seems like there may be some kind of disconnect with the username/password I'm setting up, vs the one the site is using which may be the reason this is occurring. 🤷‍♂ Just a guess

**Comment by StellaJaneRasmussen** [comment]
Interesting - that's different than what I've been dealing with. Does this happen on other branches for you?

**Comment by mjidris** [comment]
Yes it does happen on other branches sometimes. Typically, I'll stop & start the iron shell a couple times, maybe clear out and delete all the docker images manually and restart docker. After a couple tries, it usually ends up working.

**Review by JeffFallis — APPROVED** [review]
Got `localhost:3001`, but the layout is off. Might be local to my machine not sure
image

`localhost:8001` loads up just fine
image

**Review by ccqian-asu — APPROVED** [review]

**Pull request merged**
