### PR TITLE
US-81 T-94 Containerize the React application using Docker

### PR DESCRIPTION
**Pull request by StellaJaneRasmussen**
## Objective
Containerize the client-side React application

## Detailed Description
This change will function to create a Docker container containing the client-side application for the Iron Meteorite Database project. A future PR will be opened to integrate this with the automatic process for building the entire project.

## Screenshot (if applicable)
N/A

## How to Test (if applicable)
1. Navigate to the `client` directory via a CLI.
2. Run the following command to build the docker image:
`docker build -t meteorite:client .`
3. Run the following command to run the docker container:
`docker run -v ${PWD}:/app -v /app/node_modules -p 8001:8000 --rm meteorite:client`
4. Using a browser, navigate to `localhost:8001` or `127.0.0.1:8001`

## Tests (if added)
N/A

## Requirements
[Taiga User Story](https://tree.taiga.io/project/cbrobsto-iron-db/us/81)
[Taiga Task](https://tree.taiga.io/project/cbrobsto-iron-db/task/94)

### CODE REVIEW

**Comment by JeffFallis** [comment]
Having trouble with this one. When I run `docker build -t meteorite:client`, I get a message saying `"docker build" requires exactly 1 argument`

**Comment by StellaJaneRasmussen** [comment]
@JeffFallis Thanks for the catch. I realize I had a mistake in my instructions. Try `docker build -t meteorite:client .`

**Comment by JeffFallis** [comment]
different error now
image

**Comment by StellaJaneRasmussen** [comment]
What do you get when you run `ls -la`?

**Comment by JeffFallis** [comment]
i got it now, I was on a different branch without a dockerfile in the directory

**Comment by JeffFallis** [comment]
@JonathanJamesRasmussen I can load up the page using `localhost:8001`, but not `127.0.0.1:8001`. However, it does run on `127.0.0.1:8000`. Is this right?

**Comment by StellaJaneRasmussen** [comment]
If you can load up `localhost`, you should be fine. The 8000 port will be internal to the Docker bridge network for this project, so if we needed to connect the it from, say, the API container, we would connect to port 8000.

**Review by JeffFallis — APPROVED** [review]
Docker container successfully spins up and I can open the application on localhost:8001

**Comment by ccqian-asu** [comment]
Spins up and builds. I'm able to access it on port 8000.

**Review by ccqian-asu — APPROVED** [review]

**Pull request merged**
