### PR TITLE
US291: Fix Authentication Bug

### PR DESCRIPTION
**Pull request by mjidris**
## Objective
Fix an authentication bug.

## Detailed Description
There was a weird authentication bug that would prevent authenticated user sessions to persist over browser sessions. Originally I tried to make some changes to the session cookie produced by our backend API thinking this was perhaps an express-session issue. 

It turns out that this was in fact a client side issue. We use the `Auth` component as a source of truth to determine authentication state. On app startup, we were setting `isAuthenticated = false` by default thereby ignoring the presence of any auth cookies that was present in the browser from a previous session.

This made the fix relatively simple. Rather than setting the default value as false, we just check to see if a `username` cookie is present and use that to determine our initial authentication state.

## How to Test (if applicable)
1. Navigate to `http://localhost:8001` and sign into an account.
2. Navigate to a protected route (eg. panel or data entry).
3. Refresh the page, observe you are still authenticated and are on the protected page.

## Requirements
[Taiga User Story](https://tree.taiga.io/project/cbrobsto-iron-db/us/291)
[Taiga Task](https://tree.taiga.io/project/cbrobsto-iron-db/task/292)

### CODE REVIEW

**Comment by CBrobsto** [comment]
Looks like there is a conflict.

**Comment by mjidris** [comment]
> Looks like there is a conflict.

Thanks for catching this. I'll resolve those and push an update.

**Comment by StellaJaneRasmussen** [comment]
It's looking like this needs to be updated with the latest branch pushed (The API endpoints one). I think if you fix the endpoints in `app.js` in the API, it should work.

**Comment by StellaJaneRasmussen** [comment]
Oops, that may have just been local. Give me a moment.

**Comment by mjidris** [comment]
> Oops, that may have just been local. Give me a moment.

@JonathanJamesRasmussen Let me know if you're getting any API related issues. I back-merged my branch after #40 got merged in so there shouldn't be, but if there is I can take a closer look and resolve that issue.

**Comment by StellaJaneRasmussen** [comment]
@mjidris , The login is still broken for me after doing a fresh install

**Comment by StellaJaneRasmussen** [comment]
I think I figured out the issue. I had a previous branch we pushed in that had some fixes, but I hadn't updated the actual template file. I'll go ahead and update that here and push it up to this branch. Fingers crossed that'll help fix this.

**Comment by CBrobsto** [comment]
I tried testing but was unable to log in or register on a fresh install.

**Comment by mjidris** [comment]
@CBrobsto yeah I'm not sure what's going on. I back-merged with @JonathanJamesRasmussen's api fixes which should've resolved the 500 responses on register & log in, but it's not working at all. 

I need to do some more investigating to see what the issue is since I haven't actually touched any of the backend code here.

**Review by StellaJaneRasmussen — APPROVED** [review]
This worked on my end, so I'll approve it here.

**Comment by mjidris** [comment]
Pushed a commit to revert the register & api paths back to `/api/rest-of-path`. Should work now with container rebuilds.

**Review by ccqian-asu — APPROVED** [review]

**Pull request merged**
